### ISSUE TITLE
Allow modifying the hosts list of the SSH provider programatically

### ISSUE THREAD

**Issue by idanarye** [miversen33/netman.nvim#171]
The SSH provider reads the list from `~/.ssh/config`. This can be very limiting when the list of remote machines you need to work with changes dynamically (some cloud workflows), or when `~/.ssh/config` is mostly rules on patterns rather than a single concrete hostname per entry.

It would be nice if we could have a Lua API to change that list on the fly.

**Comment by miversen33** [comment]
Duplicate of #87 

You're absolutely right. Its on my list, just have some bigger fish to fry first :)
