### ISSUE TITLE
Figure out how to "override" `cwd`

### ISSUE THREAD

**Issue by miversen33** [miversen33/netman.nvim#36]
Alot of file managers rely on `cwd` to figure out what to open. If we are not setting this, they will ignore the remote file/directory we are in. Consider how to implement this safely without breaking other plugins outside the Netman system

**Comment by fdschmidt93** [comment]
Great to see this coming slowly to fruition :) I might eventually look into supporting `plenary` (no promises, `telescope` and `telescope-file-browser` keep me busy :sweat_smile: ).

Since I saw this something like

```lua
vim.loop.cwd = setmetatable({
  remote = true,
  netman = function()
    return "ssh"
  end,
  -- retain original funcref
  uv = vim.loop.cwd,
}, {
  __call = function(self, ...)
    if self.remote then
      return self.netman(...)
    else
      return self.uv(...)
    end
  end,
})
```

came to mind and tackle this as it should work safely with `remote` here being the switch (and toggle methods can be added etc.).

**Comment by miversen33** [comment]
> E: I virtually have no idea yet as to how netman works (yet), but just circulating the thought here that if netman were to inject it's providers straight into libuv, that by design factually speaking all vim.loop-based file explorers would be (at least close to) supported out-of-the-box?
This is exactly the approach I am looking into. I am able to get it working via **very jank** passthrough methods but I really hate it. That said, I don't know that I have an alternative so I may have to go that route. 

I wasn't looking into the metatables bit though, I was doing some more significantly more awful introspection to passthrough lol.

I will (hopefully) have some developer based documentation up by the end of the week that will walk through how [api](https://github.com/miversen33/netman.nvim/blob/main/lua/netman/api.lua) and [the ssh provider](https://github.com/miversen33/netman.nvim/blob/main/lua/netman/providers/ssh.lua) work and hopefully that will help people looking into the code.

But ya, I think masking libuv is going to be the route to go and if done right (and I do some cwd shenanigans), this will allow most file managers to [just work](https://www.youtube.com/watch?v=YPN0qhSyWy8&vl=en)

**Comment by miversen33** [comment]
As I apparently dont know how to use Github, this is being worked on (along with #28) in branch [issue-28-libuv-shenanigans](https://github.com/miversen33/netman.nvim/tree/issue-28-libuv-shenanigans)
I will be updating issue #28  with further info on this and closing this issue out as a duplicate
