### ISSUE TITLE
Overhaul Utils

### ISSUE THREAD

**Issue by miversen33** [miversen33/netman.nvim#78]
Everything else has been rewritten to perform better, be more maintainable, etc. But poor netman.tools.utils is still an absolute spaghetti mess of first pass code and that needs to be fixed. Do that.

**Comment by miversen33** [comment]
Welp, I guess we will need to pull this into 1.1 since I need to modify how utils does "things" in order to be async compliant :upside_down_face: 

I am never gonna get done with this milestone, I swear

**Comment by luxus** [comment]
:D

**Comment by miversen33** [comment]
The deed is done. The new utils module is not accessible (and mostly) works from an async context, as does logging. Resuming work on #117
